server {
    listen 8080;
    host localhost;
    root ./www;
    index index.html;

    server_name localhost;

    client_max_body_size 1048576;

    autoindex off;
    
    location / {
        allow_methods GET POST DELETE;
        root ./www;
        index index.html;
    }

    location /upload {
        root ./www/uploads;
        allow_methods GET POST DELETE;
    }
}

server {
    listen 8081;
    host localhost;
    root ./www;
    index index.html;

    server_name localhost;
    
    client_max_body_size 1024;

    autoindex off;

    location / {
        allow_methods GET POST DELETE;
        root ./www;
        index index.html;
    }
}