server {
    listen 8560;
    host 127.0.0.1;
    root www/site_default;
    index index.html;

    client_max_body_size 5M;

    location / {
        allow_methods GET POST DELETE;
        root www/site_default;
        index index.html;
    }

    location /cgi-bin {
        allow_methods GET POST;
        root www/cgi-bin;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
    }
}
